//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agricultural_Web_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int id { get; set; }
        public string pname { get; set; }
        public string description { get; set; }
        public string pimage { get; set; }
        public Nullable<int> price { get; set; }
        public string category { get; set; }
        public Nullable<System.DateTime> production_date { get; set; }
        public Nullable<int> uid { get; set; }
    
        public virtual User User { get; set; }
    }
}
